apiVersion: v1
kind: Service
metadata:
  name: students-management-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: students-management
  ports:
    - port: 8080
      targetPort: 8089
      nodePort: 30089