apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: students-management
  ports:
  - port: 8089        # ✅ CORRECT
    targetPort: 8089  # ✅ CORRECT
    nodePort: 30089   # ✅ CORRECT